list_user_ops_managed1:
  - ops1
  - ops2
  - ops3
  - ops4
  - ops5
  - ops6
  - ops7
  - ops8
  - ops9
  - ops10
  - ops11
  - ops12
  - ops13
  - ops14
  - ops15
  - ops16
  - ops17
  - ops18
  - ops19
  - ops20
  - ops21
  - ops22
  - ops23
  - ops24
  - ops25
  - ops26
  - ops27
  - ops28
  - ops29
  - ops30
  - ops31
  - ops32
  - ops33
  - ops34
  - ops35
  - ops36
  - ops37
  - ops38
  - ops39
  - ops40
  - ops41
  - ops42
  - ops43
  - ops44
  - ops45
  - ops46
  - ops47
  - ops48
  - ops49
  - ops50

list_user_dev_managed1:
  - dev1
  - dev2
  - dev3
  - dev4
  - dev5
  - dev6
  - dev7
  - dev8
  - dev9
  - dev10
  - dev11
  - dev12
  - dev13
  - dev14
  - dev15
  - dev16
  - dev17
  - dev18
  - dev19
  - dev20
  - dev21
  - dev22
  - dev23
  - dev24
  - dev25
  - dev26
  - dev27
  - dev28
  - dev29
  - dev30
  - dev31
  - dev32
  - dev33
  - dev34
  - dev35
  - dev36
  - dev37
  - dev38
  - dev39
  - dev40
  - dev41
  - dev42
  - dev43
  - dev44
  - dev45
  - dev46
  - dev47
  - dev48
  - dev49
  - dev50