list_user_ops_managed2:
  - ops51
  - ops52
  - ops53 
  - ops54
  - ops55
  - ops56
  - ops57
  - ops58
  - ops59
  - ops60
  - ops61
  - ops62
  - ops63
  - ops64
  - ops65
  - ops66
  - ops67
  - ops68
  - ops69
  - ops70
  - ops71
  - ops72
  - ops73
  - ops74
  - ops75
  - ops76
  - ops77
  - ops78
  - ops79
  - ops80
  - ops81
  - ops82
  - ops83
  - ops84
  - ops85
  - ops86
  - ops87
  - ops88
  - ops89
  - ops90
  - ops91
  - ops92
  - ops93
  - ops94
  - ops95
  - ops96
  - ops97
  - ops98
  - ops99
  - ops100

list_user_dev_managed2:
  - dev51
  - dev52
  - dev53 
  - dev54
  - dev55
  - dev56
  - dev57
  - dev58
  - dev59
  - dev60
  - dev61
  - dev62
  - dev63
  - dev64
  - dev65
  - dev66
  - dev67
  - dev68
  - dev69
  - dev70
  - dev71
  - dev72
  - dev73
  - dev74
  - dev75
  - dev76
  - dev77
  - dev78
  - dev79
  - dev80
  - dev81
  - dev82
  - dev83
  - dev84
  - dev85
  - dev86
  - dev87
  - dev88
  - dev89
  - dev90
  - dev91
  - dev92
  - dev93
  - dev94
  - dev95
  - dev96
  - dev97
  - dev98
  - dev99
  - dev100